config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[show edit update destroy]

  def index
    @articles = Article.all
  end

  def show; end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      flash[:notice] = "Article was successfully created."
      redirect_to @article
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    @article.update(article_params)
    if @article.save
      redirect_to @article
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @article.destroy
    redirect_to articles_url, status: :see_other
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_with model: @article do |a| %>
  <div class='mb-3'>
    <%= a.label :title, class: 'form-label' %>
    <%= a.text_field :title, class: 'form-control' %>
  </div>
  <div class='mb-3'>
    <%= a.label :content, class: 'form-label' %>
    <div id="ace-editor" style="height: 300px; width: 100%;" class="form-control"></div>
    <%= a.hidden_field :content, id: 'article_content' %>
  </div>
  <%= a.submit a.object.new_record? ? "Create Article" : "Update Article", class: 'btn btn-primary' %>
<% end %>

app/views/articles/edit.html.erb
<nav class="navbar d-flex navbar-light bg-light p-3">
  <h5 class="fw-normal">Wikinimous</h5>

  <div class="d-flex">
    <a class="btn btn-primary" href="/articles/new">New Article</a>
  </div>
</nav>

<div class='container w-75 p-3'>
  <h2 class="display-4 fw-normal">Editing Article</h2>

  <%= render 'form', article: @article %>

  <div class="mt-3">
    <%= link_to "Show", article_path %> | <%= link_to "Back", articles_path %>
  </div>
</div>

app/views/articles/index.html.erb
<nav class="navbar d-flex navbar-light bg-light p-3">
  <h5 class="fw-normal">Wikinimous</h5>

  <div class="d-flex">
    <a class="btn btn-primary" href="/articles/new">New Article</a>
  </div>
</nav>

<div class="container w-50 p-3">
  <% @articles.each do |article| %>
    <h2><%= link_to article.title, article_path(article.id), id: "no-decoration" %></h2>
    <h5 class="font-roboto fw-light"><%= truncate(article.content, length: 50, separator: '', omission: '...') %></h5>
  <% end %>
</div>

app/views/articles/new.html.erb
<nav class="navbar d-flex navbar-light bg-light p-3">
  <h5 class="fw-normal">Wikinimous</h5>

  <div class="d-flex">
    <a class="btn btn-primary" href="/articles/new">New Article</a>
  </div>
</nav>

<div class='container w-75 p-4'>
  <h2 class="display-4 fw-normal">New Article</h2>

  <%= render 'form', article: @article %>

  <div class="mt-3">
    <%= link_to "Back", articles_path %>
  </div>
</div>

app/views/articles/show.html.erb
<nav class="navbar d-flex navbar-light bg-light p-3">
  <h5 class="fw-normal">Wikinimous</h5>

  <div class="d-flex">
    <a class="btn btn-primary" href="/articles/new">New Article</a>
  </div>
</nav>

<% if flash[:notice] %>
  <div class="alert alert-info w-50 centered-alert">
    <%= flash[:notice] %>
  </div>
<% end %>

<div class="container w-50 mt-4">
  <div class="d-flex justify-content-between">
    <h2 class="fw-normal pb-3 mr-3"><%= @article.title %><h2>
    <%= link_to raw('<i class="fa-solid fa-pen"></i>'), edit_article_path %>
    <%= link_to raw('<i class="fa-solid fa-trash"></i>'), article_path(@article.id), data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this article?" } %>
  </div>
  <hr>
  <blockquote class="blockquote">
    <p><%= @article.content %></p>
    <p><%= @article.content %></p>
    <footer class="blockquote-footer m-4">Someone famous in <cite title="Source Title">Source Title</cite></footer>
  </blockquote>
  <hr>
  <div class="container">
    <h4 class="fw-normal display-8 pb-3 mr-3">Feel free to leave your comments here!</h4>
    <div class="form-floating">
    <textarea class="form-control" placeholder="Leave a comment here" id="floatingTextarea2" style="height: 100px"></textarea>
    <label for="floatingTextarea2">Comments</label>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWikinimous</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Merriweather:ital,wght@0,300;0,400;0,700;0,900;1,300;1,400;1,700;1,900&display=swap" rel="stylesheet">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/ace/1.4.12/ace.js"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>